// test/annotation.test.js
// FAILING SPEC (red) for the frame-annotation surface (PRD §4.8 / HANDOFF §4).
// Build side: seed the 'annotations' store, build, assert the PNG is emitted.
// The drawing UI (canvas, pen/arrow/circle, mouse) is BROWSER-GATED and not here.
//
// CONTRACT:
//   * New IndexedDB store 'annotations' holds rows { name, dataUrl, t, route }
//     where name is '<YYYY-MM-DD_HH-MM-SS.mmm>_annotated.png' (a PNG data URL).
//   * lib/package.js build() emits each annotation as a file named by .name (the
//     '*_annotated.png' the /audit step classifies as a screenshot frame).
//   * store.clearAll() also clears 'annotations'.
//
// HINTS (do NOT edit this file): store.js — add 'annotations' store, bump
// DB_VERSION, add to clearAll(). package.js — read 'annotations', and for each
// root.file(a.name, dataUrlToUint8(a.dataUrl)).

const test = require('node:test');
const assert = require('node:assert/strict');

require('fake-indexeddb/auto');
global.self = global;
global.JSZip = require('../lib/jszip.min.js');
require('../lib/store.js');
require('../lib/package.js');

const PNG = 'data:image/png;base64,' + Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a]).toString('base64');

async function buildZip() {
  const pkg = await self.AuditPackage.build({ title: 'demo', startedAt: Date.parse('2026-06-28T14:30:00Z') });
  const zip = await JSZip.loadAsync(Buffer.from(pkg.dataUrl.split(',')[1], 'base64'));
  return { pkg, zip };
}
const fileNames = (zip) => Object.keys(zip.files).map((p) => p.split('/').pop());

test('annotated PNGs are emitted into the package', async () => {
  await self.AuditStore.clearAll();
  await self.AuditStore.put('annotations', {
    name: '2026-06-28_14-30-05.123_annotated.png',
    dataUrl: PNG,
    t: Date.parse('2026-06-28T14:30:05Z'),
    route: '/dash',
  });
  const { zip } = await buildZip();
  const names = fileNames(zip);
  assert.ok(names.some((n) => /_annotated\.png$/.test(n)), 'an *_annotated.png must be in the package');
  assert.ok(names.includes('2026-06-28_14-30-05.123_annotated.png'), 'emitted under its own name');
});

test('clearAll() also clears the annotations store', async () => {
  await self.AuditStore.put('annotations', { name: 'x_annotated.png', dataUrl: PNG, t: 1, route: '/' });
  await self.AuditStore.clearAll();
  const { zip } = await buildZip();
  assert.ok(!fileNames(zip).some((n) => /_annotated\.png$/.test(n)), 'no annotations should remain');
});
