// test/console.test.js
// FAILING SPEC (red) for the Phase 2 `console.txt` output-package surface.
// This is the loop's target: it is committed red, the loop drives it green by
// implementing the BUILD side only. The capture side (chrome.debugger tap in
// lib/debugger-tap.js) is browser-gated and is NOT tested here.
//
// CONTRACT this defines (HANDOFF.md §4 / PRD.md §4.5):
//   * A new IndexedDB store 'console' holds rows: { t, route, level, message }
//     where level is 'error' | 'warning'.
//   * lib/package.js build() ALWAYS emits a `console.txt` into the audit folder
//     (present even when empty, like narration.txt), with one line per row:
//         [HH-MM-SS.mmm] (/route) LEVEL: message
//     LEVEL is the level upper-cased (ERROR / WARNING). Lines sorted ascending by t.
//   * build().counts includes `console`.
//   * store.clearAll() also clears the 'console' store (no leak between sessions).
//
// IMPLEMENTATION HINTS for whoever makes this green (do NOT edit this file):
//   - store.js: add the 'console' object store AND bump DB_VERSION so existing
//     browser DBs get it via onupgradeneeded; add 'console' to clearAll()'s list.
//   - package.js: read 'console', format + sort, root.file('console.txt', ...),
//     add console count to the returned counts.
//   - DO NOT change any existing filename or JSON shape (contract.test.js guards them).

const test = require('node:test');
const assert = require('node:assert/strict');

require('fake-indexeddb/auto');
global.self = global;
global.JSZip = require('../lib/jszip.min.js');
require('../lib/store.js');
require('../lib/package.js');

const CONSOLE_LINE_RE = /^\[\d{2}-\d{2}-\d{2}\.\d{3}\] \(.+\) (ERROR|WARNING): .+/;

async function buildZip() {
  const pkg = await self.AuditPackage.build({ title: 'demo', startedAt: Date.parse('2026-06-28T14:30:00Z') });
  const zip = await JSZip.loadAsync(Buffer.from(pkg.dataUrl.split(',')[1], 'base64'));
  return { pkg, zip };
}

function readFile(zip, suffix) {
  const path = Object.keys(zip.files).find((p) => p.endsWith(suffix));
  return path ? zip.files[path].async('string') : null;
}

test('console.txt is present even when no console events were captured', async () => {
  await self.AuditStore.clearAll();
  const { zip } = await buildZip();
  const txt = await readFile(zip, 'console.txt');
  assert.notEqual(txt, null, 'console.txt must always be emitted');
  assert.equal(txt.trim(), '', 'with no events it should be empty');
});

test('console.txt renders seeded events as [time] (route) LEVEL: message', async () => {
  await self.AuditStore.clearAll();
  const base = Date.parse('2026-06-28T14:30:00Z');
  // Inserted out of chronological order to prove build() sorts by t.
  await self.AuditStore.put('console', { t: base + 4000, route: '/dashboard', level: 'warning', message: 'Deprecated API used' });
  await self.AuditStore.put('console', { t: base + 1000, route: '/login', level: 'error', message: 'Uncaught TypeError: x is undefined' });

  const { zip } = await buildZip();
  const txt = (await readFile(zip, 'console.txt')).trim();
  const lines = txt.split('\n').filter(Boolean);

  assert.equal(lines.length, 2);
  for (const line of lines) assert.match(line, CONSOLE_LINE_RE);

  // Sorted ascending by t: the error (t+1000) comes before the warning (t+4000).
  assert.match(lines[0], /\(\/login\) ERROR: Uncaught TypeError/);
  assert.match(lines[1], /\(\/dashboard\) WARNING: Deprecated API used/);
});

test('build().counts includes a console count', async () => {
  await self.AuditStore.clearAll();
  const base = Date.parse('2026-06-28T14:30:00Z');
  await self.AuditStore.put('console', { t: base, route: '/', level: 'error', message: 'boom' });
  const { pkg } = await buildZip();
  assert.equal(pkg.counts.console, 1);
});

test('clearAll() also clears the console store (no leak between sessions)', async () => {
  const base = Date.parse('2026-06-28T14:30:00Z');
  await self.AuditStore.put('console', { t: base, route: '/', level: 'error', message: 'stale' });
  await self.AuditStore.clearAll();
  const { zip } = await buildZip();
  const txt = await readFile(zip, 'console.txt');
  assert.equal(txt.trim(), '', 'clearAll must wipe console rows from a prior session');
});
