// test/debugger-tap.test.js
// FAILING SPEC (red) for capture-side gaps, plus guards for behavior that works.
// Tests the chrome.debugger event MAPPING by mocking chrome.debugger — no browser.
// (Whether Chrome delivers these events stays browser-gated; this proves we handle them.)
//
// CONTRACT for lib/debugger-tap.js:
//   * onCdpEvent maps Runtime.consoleAPICalled (type error|warning) and
//     Log.entryAdded (level error|warning) to { t, route, level, message }.
//     log/info/debug are dropped.
//   * Runtime.exceptionThrown (uncaught JS errors) -> level:'error' row.
//   * detach({tabId}) calls chrome.debugger.detach even with no in-memory record.
//   * A failed chrome.debugger.attach leaves no dangling listeners.
//   * GAP #2a: row.t uses the CDP event's own timestamp, not Date.now(), so
//     events sort correctly (consoleAPICalled.timestamp / Log entry.timestamp /
//     exceptionThrown.timestamp; fall back to Date.now() only if absent).
//   * GAP #2b: attach({ since }) drops events whose timestamp predates `since`
//     (the session start) — this is how replayed pre-session entries are excluded.
//
// DO NOT edit this file to pass — fix lib/debugger-tap.js.

const test = require('node:test');
const assert = require('node:assert/strict');

function makeChrome() {
  const eventListeners = [];
  const detachListeners = [];
  const calls = { attach: [], sendCommand: [], detach: [] };
  let failAttach = false;
  return {
    _fire(source, method, params) { for (const f of [...eventListeners]) f(source, method, params); },
    _calls: calls,
    _counts: () => ({ event: eventListeners.length, detach: detachListeners.length }),
    _failAttach(v) { failAttach = v; },
    debugger: {
      onEvent: {
        addListener: (f) => eventListeners.push(f),
        removeListener: (f) => { const i = eventListeners.indexOf(f); if (i >= 0) eventListeners.splice(i, 1); },
      },
      onDetach: {
        addListener: (f) => detachListeners.push(f),
        removeListener: (f) => { const i = detachListeners.indexOf(f); if (i >= 0) detachListeners.splice(i, 1); },
      },
      attach: async () => { calls.attach.push(true); if (failAttach) throw new Error('Another debugger is already attached'); },
      sendCommand: async (target, method) => { calls.sendCommand.push(method); },
      detach: async (target) => { calls.detach.push(target); },
    },
  };
}

global.self = global;
global.chrome = makeChrome();
const tap = require('../lib/debugger-tap.js');

test.beforeEach(() => { global.chrome = makeChrome(); });

test('console.error -> error row with message and route', async () => {
  const rows = [];
  await tap.attach({ tabId: 1, getRoute: () => '/login', onEvent: (r) => rows.push(r) });
  global.chrome._fire({ tabId: 1 }, 'Runtime.consoleAPICalled', { type: 'error', args: [{ value: 'boom' }] });
  assert.equal(rows.length, 1);
  assert.equal(rows[0].level, 'error');
  assert.equal(rows[0].message, 'boom');
  assert.equal(rows[0].route, '/login');
  assert.equal(typeof rows[0].t, 'number');
  await tap.detach({ tabId: 1 });
});

test('console.warn -> warning row', async () => {
  const rows = [];
  await tap.attach({ tabId: 2, getRoute: () => '/', onEvent: (r) => rows.push(r) });
  global.chrome._fire({ tabId: 2 }, 'Runtime.consoleAPICalled', { type: 'warning', args: [{ value: 'deprecated' }] });
  assert.equal(rows.length, 1);
  assert.equal(rows[0].level, 'warning');
  await tap.detach({ tabId: 2 });
});

test('console.log/info/debug are dropped', async () => {
  const rows = [];
  await tap.attach({ tabId: 3, getRoute: () => '/', onEvent: (r) => rows.push(r) });
  global.chrome._fire({ tabId: 3 }, 'Runtime.consoleAPICalled', { type: 'log', args: [{ value: 'noise' }] });
  global.chrome._fire({ tabId: 3 }, 'Runtime.consoleAPICalled', { type: 'info', args: [{ value: 'noise' }] });
  assert.equal(rows.length, 0);
  await tap.detach({ tabId: 3 });
});

test('Log.entryAdded (network/CSP) -> row', async () => {
  const rows = [];
  await tap.attach({ tabId: 4, getRoute: () => '/assets', onEvent: (r) => rows.push(r) });
  global.chrome._fire({ tabId: 4 }, 'Log.entryAdded', { entry: { level: 'error', text: 'Failed to load resource: 404' } });
  assert.equal(rows.length, 1);
  assert.equal(rows[0].level, 'error');
  assert.match(rows[0].message, /404/);
  await tap.detach({ tabId: 4 });
});

test('uncaught exception (Runtime.exceptionThrown) is captured as an error', async () => {
  const rows = [];
  await tap.attach({ tabId: 5, getRoute: () => '/checkout', onEvent: (r) => rows.push(r) });
  global.chrome._fire({ tabId: 5 }, 'Runtime.exceptionThrown', {
    exceptionDetails: { text: 'Uncaught', exception: { description: 'TypeError: x is undefined\n    at app.js:1:1' } },
  });
  assert.equal(rows.length, 1);
  assert.equal(rows[0].level, 'error');
  assert.match(rows[0].message, /TypeError: x is undefined/);
  await tap.detach({ tabId: 5 });
});

test('detach() clears the debugger with no in-memory attachment (post-respawn)', async () => {
  await tap.detach({ tabId: 9 });
  assert.deepEqual(global.chrome._calls.detach, [{ tabId: 9 }]);
});

test('attach() leaves no dangling listeners if chrome.debugger.attach fails', async () => {
  global.chrome._failAttach(true);
  await assert.rejects(tap.attach({ tabId: 7, onEvent: () => {} }));
  assert.deepEqual(global.chrome._counts(), { event: 0, detach: 0 });
});

// --- GAP #2a (red): use the event's own timestamp ----------------------------
test('row.t uses the CDP event timestamp, not Date.now()', async () => {
  const rows = [];
  await tap.attach({ tabId: 11, getRoute: () => '/', onEvent: (r) => rows.push(r) });
  global.chrome._fire({ tabId: 11 }, 'Runtime.consoleAPICalled', { type: 'error', args: [{ value: 'x' }], timestamp: 1000000 });
  assert.equal(rows.length, 1);
  assert.equal(rows[0].t, 1000000, 'must use the event timestamp so pre-session events sort correctly');
  await tap.detach({ tabId: 11 });
});

// --- GAP #2b (red): drop pre-session (replayed) events -----------------------
test('events older than the session start (since) are dropped', async () => {
  const rows = [];
  await tap.attach({ tabId: 12, since: 5000, getRoute: () => '/', onEvent: (r) => rows.push(r) });
  global.chrome._fire({ tabId: 12 }, 'Runtime.consoleAPICalled', { type: 'error', args: [{ value: 'stale' }], timestamp: 4000 });
  global.chrome._fire({ tabId: 12 }, 'Runtime.consoleAPICalled', { type: 'error', args: [{ value: 'live' }], timestamp: 6000 });
  assert.equal(rows.length, 1, 'pre-session replayed events must be dropped');
  assert.equal(rows[0].message, 'live');
  await tap.detach({ tabId: 12 });
});
