// test/debugger-tap.test.js
// FAILING SPEC (red) for two capture-side gaps the green console.txt loop missed,
// plus guards for the behavior it got right. Tests the chrome.debugger event
// MAPPING by mocking chrome.debugger — no browser needed. (Whether Chrome actually
// delivers these events stays browser-gated; this only proves we handle them.)
//
// CONTRACT this defines for lib/debugger-tap.js:
//   * onCdpEvent maps Runtime.consoleAPICalled (type error|warning) and
//     Log.entryAdded (level error|warning) to { t, route, level, message }.
//     log/info/debug are dropped.
//   * GAP #1: Runtime.exceptionThrown (uncaught JS errors — the classic red error
//     on screen) MUST be captured as a level:'error' row, message taken from
//     exceptionDetails.exception.description (fallback exceptionDetails.text).
//     Note: Runtime.enable already delivers exceptionThrown — no extra sendCommand
//     is needed, only handling in onCdpEvent.
//   * GAP #2: detach({tabId}) MUST call chrome.debugger.detach even when there is
//     no in-memory attachment record (e.g. after a worker respawn) so the
//     "is being debugged" banner always clears on Stop.
//   * Robustness: a failed chrome.debugger.attach must leave no dangling listeners.
//
// DO NOT edit this file to make it pass — fix lib/debugger-tap.js.

const test = require('node:test');
const assert = require('node:assert/strict');

function makeChrome() {
  const eventListeners = [];
  const detachListeners = [];
  const calls = { attach: [], sendCommand: [], detach: [] };
  let failAttach = false;
  return {
    _fire(source, method, params) { for (const f of [...eventListeners]) f(source, method, params); },
    _calls: calls,
    _counts: () => ({ event: eventListeners.length, detach: detachListeners.length }),
    _failAttach(v) { failAttach = v; },
    debugger: {
      onEvent: {
        addListener: (f) => eventListeners.push(f),
        removeListener: (f) => { const i = eventListeners.indexOf(f); if (i >= 0) eventListeners.splice(i, 1); },
      },
      onDetach: {
        addListener: (f) => detachListeners.push(f),
        removeListener: (f) => { const i = detachListeners.indexOf(f); if (i >= 0) detachListeners.splice(i, 1); },
      },
      attach: async () => { calls.attach.push(true); if (failAttach) throw new Error('Another debugger is already attached'); },
      sendCommand: async (target, method) => { calls.sendCommand.push(method); },
      detach: async (target) => { calls.detach.push(target); },
    },
  };
}

global.self = global;
global.chrome = makeChrome();
const tap = require('../lib/debugger-tap.js');

test.beforeEach(() => { global.chrome = makeChrome(); });

test('console.error -> error row with message and route', async () => {
  const rows = [];
  await tap.attach({ tabId: 1, getRoute: () => '/login', onEvent: (r) => rows.push(r) });
  global.chrome._fire({ tabId: 1 }, 'Runtime.consoleAPICalled', { type: 'error', args: [{ value: 'boom' }] });
  assert.equal(rows.length, 1);
  assert.equal(rows[0].level, 'error');
  assert.equal(rows[0].message, 'boom');
  assert.equal(rows[0].route, '/login');
  assert.equal(typeof rows[0].t, 'number');
  await tap.detach({ tabId: 1 });
});

test('console.warn -> warning row', async () => {
  const rows = [];
  await tap.attach({ tabId: 2, getRoute: () => '/', onEvent: (r) => rows.push(r) });
  global.chrome._fire({ tabId: 2 }, 'Runtime.consoleAPICalled', { type: 'warning', args: [{ value: 'deprecated' }] });
  assert.equal(rows.length, 1);
  assert.equal(rows[0].level, 'warning');
  await tap.detach({ tabId: 2 });
});

test('console.log/info/debug are dropped', async () => {
  const rows = [];
  await tap.attach({ tabId: 3, getRoute: () => '/', onEvent: (r) => rows.push(r) });
  global.chrome._fire({ tabId: 3 }, 'Runtime.consoleAPICalled', { type: 'log', args: [{ value: 'noise' }] });
  global.chrome._fire({ tabId: 3 }, 'Runtime.consoleAPICalled', { type: 'info', args: [{ value: 'noise' }] });
  assert.equal(rows.length, 0);
  await tap.detach({ tabId: 3 });
});

test('Log.entryAdded (network/CSP) warning -> warning row', async () => {
  const rows = [];
  await tap.attach({ tabId: 4, getRoute: () => '/assets', onEvent: (r) => rows.push(r) });
  global.chrome._fire({ tabId: 4 }, 'Log.entryAdded', { entry: { level: 'error', text: 'Failed to load resource: 404' } });
  assert.equal(rows.length, 1);
  assert.equal(rows[0].level, 'error');
  assert.match(rows[0].message, /404/);
  await tap.detach({ tabId: 4 });
});

// --- GAP #1 (red): uncaught exceptions ---------------------------------------
test('uncaught exception (Runtime.exceptionThrown) is captured as an error', async () => {
  const rows = [];
  await tap.attach({ tabId: 5, getRoute: () => '/checkout', onEvent: (r) => rows.push(r) });
  global.chrome._fire({ tabId: 5 }, 'Runtime.exceptionThrown', {
    exceptionDetails: {
      text: 'Uncaught',
      exception: { description: 'TypeError: x is undefined\n    at app.js:1:1' },
    },
  });
  assert.equal(rows.length, 1, 'uncaught exceptions are the #1 audit finding and must be captured');
  assert.equal(rows[0].level, 'error');
  assert.match(rows[0].message, /TypeError: x is undefined/);
  assert.equal(rows[0].route, '/checkout');
  await tap.detach({ tabId: 5 });
});

// --- GAP #2 (red): banner must clear even after a worker respawn --------------
test('detach() clears the debugger with no in-memory attachment (post-respawn)', async () => {
  // No attach() first — simulates the worker having been killed and respawned,
  // leaving the attachments map empty while the tab is still being debugged.
  await tap.detach({ tabId: 9 });
  assert.deepEqual(global.chrome._calls.detach, [{ tabId: 9 }],
    'must call chrome.debugger.detach so the banner clears on Stop');
});

// --- robustness (red): no dangling listeners on a failed attach --------------
test('attach() leaves no dangling listeners if chrome.debugger.attach fails', async () => {
  global.chrome._failAttach(true);
  await assert.rejects(tap.attach({ tabId: 7, onEvent: () => {} }));
  assert.deepEqual(global.chrome._counts(), { event: 0, detach: 0 },
    'failed attach must not leave onEvent/onDetach listeners registered');
});
