// test/environment.test.js
// FAILING SPEC (red) for the environment.json context header (PRD §4.7 /
// HANDOFF §3). Build side: seed the 'environment' store, build, assert the file.
//
// CONTRACT this defines:
//   * New IndexedDB store 'environment' holds a single record:
//       { viewport:{w,h}, dpr, zoom, ua, host, url, capturedAt, custom }
//     `custom` is the per-project extractor hook — an object that ships EMPTY so
//     no target-app context (e.g. Elevate tenant) leaks into the generic core.
//   * lib/package.js build() ALWAYS emits environment.json (a JSON object; {} if
//     nothing was captured).
//   * store.clearAll() also clears 'environment'.
//
// HINTS (do NOT edit this file): store.js — add 'environment' store, bump
// DB_VERSION, add to clearAll(). package.js — read 'environment', emit
// environment.json = JSON.stringify(env || {}, null, 2).

const test = require('node:test');
const assert = require('node:assert/strict');

require('fake-indexeddb/auto');
global.self = global;
global.JSZip = require('../lib/jszip.min.js');
require('../lib/store.js');
require('../lib/package.js');

async function buildZip() {
  const pkg = await self.AuditPackage.build({ title: 'demo', startedAt: Date.parse('2026-06-28T14:30:00Z') });
  const zip = await JSZip.loadAsync(Buffer.from(pkg.dataUrl.split(',')[1], 'base64'));
  return { pkg, zip };
}
function readFile(zip, suffix) {
  const p = Object.keys(zip.files).find((k) => k.endsWith(suffix));
  return p ? zip.files[p].async('string') : null;
}

const SAMPLE = {
  viewport: { w: 1280, h: 800 },
  dpr: 2,
  zoom: 1,
  ua: 'Mozilla/5.0 (Test) Chrome/130',
  host: 'localhost:8000',
  url: 'http://localhost:8000/fixtures/smoke.html',
  capturedAt: '2026-06-28T18:54:00.000Z',
  custom: {},
};

test('environment.json is present even when nothing was captured', async () => {
  await self.AuditStore.clearAll();
  const { zip } = await buildZip();
  const txt = await readFile(zip, 'environment.json');
  assert.notEqual(txt, null, 'environment.json must always be emitted');
  assert.deepEqual(JSON.parse(txt), {}, 'with nothing captured it should be an empty object');
});

test('environment.json carries the captured universal fields', async () => {
  await self.AuditStore.clearAll();
  await self.AuditStore.put('environment', SAMPLE);
  const { zip } = await buildZip();
  const env = JSON.parse(await readFile(zip, 'environment.json'));
  assert.deepEqual(env.viewport, { w: 1280, h: 800 });
  assert.equal(env.dpr, 2);
  assert.equal(typeof env.ua, 'string');
  assert.equal(env.host, 'localhost:8000');
  assert.equal(typeof env.url, 'string');
  assert.equal(typeof env.capturedAt, 'string');
});

test('environment.json ships an empty custom extractor hook', async () => {
  await self.AuditStore.clearAll();
  await self.AuditStore.put('environment', SAMPLE);
  const { zip } = await buildZip();
  const env = JSON.parse(await readFile(zip, 'environment.json'));
  assert.deepEqual(env.custom, {}, 'custom must ship empty (no target-app context in the core)');
});

test('clearAll() also clears the environment store', async () => {
  await self.AuditStore.put('environment', SAMPLE);
  await self.AuditStore.clearAll();
  const { zip } = await buildZip();
  assert.deepEqual(JSON.parse(await readFile(zip, 'environment.json')), {});
});
