// test/network.test.js
// FAILING SPEC (red) for the Phase 2 `network-errors.txt` surface — failed
// requests only (PRD §4.6 / HANDOFF §4). Build side: seed the 'network' store,
// build, assert the output file + counts. Mirrors console.test.js.
//
// CONTRACT this defines:
//   * New IndexedDB store 'network' holds rows { t, route, method, url, status }
//     where status is the HTTP status number (4xx/5xx) OR a network-level error
//     string (e.g. 'net::ERR_NAME_NOT_RESOLVED').
//   * lib/package.js build() ALWAYS emits `network-errors.txt` (present even when
//     empty), one line per row sorted ascending by t:
//         [HH-MM-SS.mmm] (/route) METHOD STATUS URL
//   * build().counts includes `network`.
//   * store.clearAll() also clears 'network'.
//
// IMPLEMENTATION HINTS (do NOT edit this file):
//   - store.js: add the 'network' object store, bump DB_VERSION, add to clearAll().
//   - package.js: read 'network', add buildNetwork(rows), root.file('network-errors.txt', ...),
//     add network count. Do not change existing filenames/shapes.

const test = require('node:test');
const assert = require('node:assert/strict');

require('fake-indexeddb/auto');
global.self = global;
global.JSZip = require('../lib/jszip.min.js');
require('../lib/store.js');
require('../lib/package.js');

const LINE_RE = /^\[\d{2}-\d{2}-\d{2}\.\d{3}\] \(.+\) [A-Z]+ \S+ \S+/;

async function buildZip() {
  const pkg = await self.AuditPackage.build({ title: 'demo', startedAt: Date.parse('2026-06-28T14:30:00Z') });
  const zip = await JSZip.loadAsync(Buffer.from(pkg.dataUrl.split(',')[1], 'base64'));
  return { pkg, zip };
}
function readFile(zip, suffix) {
  const p = Object.keys(zip.files).find((k) => k.endsWith(suffix));
  return p ? zip.files[p].async('string') : null;
}

test('network-errors.txt is present even with no failures', async () => {
  await self.AuditStore.clearAll();
  const { zip } = await buildZip();
  const txt = await readFile(zip, 'network-errors.txt');
  assert.notEqual(txt, null, 'network-errors.txt must always be emitted');
  assert.equal(txt.trim(), '');
});

test('renders seeded failures as [time] (route) METHOD STATUS URL, sorted by t', async () => {
  await self.AuditStore.clearAll();
  const base = Date.parse('2026-06-28T14:30:00Z');
  await self.AuditStore.put('network', { t: base + 3000, route: '/dash', method: 'POST', url: 'https://api.example.com/x', status: 500 });
  await self.AuditStore.put('network', { t: base + 1000, route: '/login', method: 'GET', url: 'https://api.example.com/y', status: 404 });
  const { zip } = await buildZip();
  const txt = (await readFile(zip, 'network-errors.txt')).trim();
  const lines = txt.split('\n').filter(Boolean);
  assert.equal(lines.length, 2);
  for (const l of lines) assert.match(l, LINE_RE);
  assert.match(lines[0], /\(\/login\) GET 404 https:\/\/api\.example\.com\/y/);
  assert.match(lines[1], /\(\/dash\) POST 500 https:\/\/api\.example\.com\/x/);
});

test('build().counts includes a network count', async () => {
  await self.AuditStore.clearAll();
  const base = Date.parse('2026-06-28T14:30:00Z');
  await self.AuditStore.put('network', { t: base, route: '/', method: 'GET', url: 'https://a', status: 404 });
  const { pkg } = await buildZip();
  assert.equal(pkg.counts.network, 1);
});

test('clearAll() also clears the network store', async () => {
  const base = Date.parse('2026-06-28T14:30:00Z');
  await self.AuditStore.put('network', { t: base, route: '/', method: 'GET', url: 'https://a', status: 404 });
  await self.AuditStore.clearAll();
  const { zip } = await buildZip();
  assert.equal((await readFile(zip, 'network-errors.txt')).trim(), '');
});
