// test/recorder.test.js
// Content-script harness for content/recorder.js — the in-page half (overlay,
// MARK input) that had no coverage. Loads the real recorder under jsdom with a
// mocked chrome.runtime, then drives its message handler + DOM.
//
// Red spec:
//   * MARK confirmation: after a MARK is submitted, a visible confirmation toast
//     (text matching /MARK saved/i) must appear in the page so the operator gets
//     feedback without hunting for the tiny input. Currently there is none.
// Guards (should stay green) — prove the rest of the MARK path works in-page:
//   * recorder:start builds the floating overlay.
//   * recorder:mark-prompt shows the MARK input.
//   * typing + Enter sends a { type:'mark' } runtime message.
//   * an empty MARK sends nothing.
//
// NOTE: focus/z-index/popup-overlay behavior is browser-gated and not asserted
// here; this covers the logic. DO NOT edit this file to pass — fix recorder.js.

const test = require('node:test');
const assert = require('node:assert/strict');
const { JSDOM } = require('jsdom');

const dom = new JSDOM('<!doctype html><html><body></body></html>', { url: 'http://localhost:8000/dashboard' });
global.window = dom.window;
global.document = dom.window.document;
global.location = dom.window.location;
global.Node = dom.window.Node;
global.Element = dom.window.Element;

// Don't run real timers (recorder starts a setInterval tick).
global.setInterval = () => 1;
global.clearInterval = () => {};

const sent = [];
global.chrome = {
  runtime: {
    onMessage: { addListener: (f) => { global.chrome._msg = f; } },
    sendMessage: (msg, cb) => {
      sent.push(msg);
      if (typeof cb === 'function') {
        // Resume path: report an active session so the recorder enables itself.
        if (msg && msg.type === 'session:status') cb({ ok: true, session: { active: true, intervalMs: 5000 } });
        else cb({ ok: true });
      }
    },
    lastError: null,
  },
};

require('../content/recorder.js'); // self-enables via the session:status reply

function deliver(msg) {
  return new Promise((resolve) => { global.chrome._msg(msg, {}, resolve); });
}
const hasText = (re) =>
  [...document.querySelectorAll('*')].some((el) => re.test(el.textContent || ''));

test('recorder:start builds the floating overlay', async () => {
  await deliver({ type: 'recorder:start', intervalMs: 5000 });
  assert.ok(document.getElementById('__audit_capture_overlay__'), 'overlay should exist');
});

test('recorder:mark-prompt shows the MARK input', async () => {
  await deliver({ type: 'recorder:start', intervalMs: 5000 });
  await deliver({ type: 'recorder:mark-prompt' });
  assert.ok(document.getElementById('__audit_mark_input__'), 'MARK input should appear');
});

test('typing + Enter sends a mark message', async () => {
  await deliver({ type: 'recorder:start', intervalMs: 5000 });
  await deliver({ type: 'recorder:mark-prompt' });
  const input = document.querySelector('#__audit_mark_input__ input');
  input.value = 'MARK 001 — header overlaps, verdict: bug';
  input.dispatchEvent(new dom.window.KeyboardEvent('keydown', { key: 'Enter', bubbles: true }));
  const mark = sent.find((m) => m && m.type === 'mark');
  assert.ok(mark, 'a mark message must be sent');
  assert.match(mark.text, /MARK 001/);
});

test('an empty MARK sends nothing', async () => {
  await deliver({ type: 'recorder:start', intervalMs: 5000 });
  await deliver({ type: 'recorder:mark-prompt' });
  const before = sent.filter((m) => m && m.type === 'mark').length;
  const input = document.querySelector('#__audit_mark_input__ input');
  input.value = '   ';
  input.dispatchEvent(new dom.window.KeyboardEvent('keydown', { key: 'Enter', bubbles: true }));
  const after = sent.filter((m) => m && m.type === 'mark').length;
  assert.equal(after, before, 'empty/whitespace MARK must not send');
});

// --- RED: MARK needs a visible confirmation ---------------------------------
test('submitting a MARK shows a visible confirmation toast', async () => {
  await deliver({ type: 'recorder:start', intervalMs: 5000 });
  await deliver({ type: 'recorder:mark-prompt' });
  const input = document.querySelector('#__audit_mark_input__ input');
  input.value = 'MARK 002 — spacing off, verdict: nit';
  input.dispatchEvent(new dom.window.KeyboardEvent('keydown', { key: 'Enter', bubbles: true }));
  assert.ok(hasText(/MARK saved/i), 'a confirmation toast should appear after a MARK');
});
