// test/recorder.test.js
// Content-script harness for content/recorder.js — loads the real recorder under
// jsdom with a mocked chrome.runtime, then drives its message handler + DOM.
//
// Red specs:
//   * Confirmation toast: after a MARK is submitted, a visible toast (text /MARK
//     saved/i) appears.  [done in the MARK loop — kept as a guard]
//   * #5 No self-capture: clicks/changes on the extension's OWN UI
//     (#__audit_capture_overlay__, #__audit_mark_input__) must NOT be recorded as
//     spine steps — otherwise recording.json is polluted with the auditor's tool
//     interactions instead of the app's. Fix onClick/onChange to ignore targets
//     inside those containers (e.g. target.closest('#__audit_capture_overlay__,
//     #__audit_mark_input__')).
// Guards (stay green): overlay builds, mark-prompt shows input, Enter sends mark,
//   empty mark sends nothing, and NORMAL page clicks ARE recorded.
//
// DO NOT edit this file to pass — fix content/recorder.js.

const test = require('node:test');
const assert = require('node:assert/strict');
const { JSDOM } = require('jsdom');

const dom = new JSDOM('<!doctype html><html><body></body></html>', { url: 'http://localhost:8000/dashboard' });
global.window = dom.window;
global.document = dom.window.document;
global.location = dom.window.location;
global.Node = dom.window.Node;
global.Element = dom.window.Element;

global.setInterval = () => 1;
global.clearInterval = () => {};

const sent = [];
global.chrome = {
  runtime: {
    onMessage: { addListener: (f) => { global.chrome._msg = f; } },
    sendMessage: (msg, cb) => {
      sent.push(msg);
      if (typeof cb === 'function') {
        if (msg && msg.type === 'session:status') cb({ ok: true, session: { active: true, intervalMs: 5000 } });
        else cb({ ok: true });
      }
    },
    lastError: null,
  },
};

require('../content/recorder.js');

function deliver(msg) {
  return new Promise((resolve) => { global.chrome._msg(msg, {}, resolve); });
}
const hasText = (re) => [...document.querySelectorAll('*')].some((el) => re.test(el.textContent || ''));
const stepCount = () => sent.filter((m) => m && m.type === 'step').length;
const clickStepCount = () => sent.filter((m) => m && m.type === 'step' && m.step && m.step.type === 'click').length;
const fireClick = (el) => el.dispatchEvent(new dom.window.MouseEvent('click', { bubbles: true }));

// The recorder is a singleton module; reset it between tests so state (active
// flag, an open MARK input, the overlay) doesn't leak across cases.
test.beforeEach(async () => {
  await deliver({ type: 'recorder:stop' });
  ['__audit_mark_input__', '__audit_capture_overlay__', '__audit_toast__'].forEach((id) => {
    const e = document.getElementById(id);
    if (e && e.parentNode) e.parentNode.removeChild(e);
  });
});

test('recorder:start builds the floating overlay', async () => {
  await deliver({ type: 'recorder:start', intervalMs: 5000 });
  assert.ok(document.getElementById('__audit_capture_overlay__'));
});

test('recorder:mark-prompt shows the MARK input', async () => {
  await deliver({ type: 'recorder:start', intervalMs: 5000 });
  await deliver({ type: 'recorder:mark-prompt' });
  assert.ok(document.getElementById('__audit_mark_input__'));
});

test('typing + Enter sends a mark message', async () => {
  await deliver({ type: 'recorder:start', intervalMs: 5000 });
  await deliver({ type: 'recorder:mark-prompt' });
  const input = document.querySelector('#__audit_mark_input__ input');
  input.value = 'MARK 001 — header overlaps, verdict: bug';
  input.dispatchEvent(new dom.window.KeyboardEvent('keydown', { key: 'Enter', bubbles: true }));
  const mark = sent.find((m) => m && m.type === 'mark');
  assert.ok(mark); assert.match(mark.text, /MARK 001/);
});

test('an empty MARK sends nothing', async () => {
  await deliver({ type: 'recorder:start', intervalMs: 5000 });
  await deliver({ type: 'recorder:mark-prompt' });
  const before = sent.filter((m) => m && m.type === 'mark').length;
  const input = document.querySelector('#__audit_mark_input__ input');
  input.value = '   ';
  input.dispatchEvent(new dom.window.KeyboardEvent('keydown', { key: 'Enter', bubbles: true }));
  assert.equal(sent.filter((m) => m && m.type === 'mark').length, before);
});

test('submitting a MARK shows a visible confirmation toast', async () => {
  await deliver({ type: 'recorder:start', intervalMs: 5000 });
  await deliver({ type: 'recorder:mark-prompt' });
  const input = document.querySelector('#__audit_mark_input__ input');
  input.value = 'MARK 002 — spacing off, verdict: nit';
  input.dispatchEvent(new dom.window.KeyboardEvent('keydown', { key: 'Enter', bubbles: true }));
  assert.ok(hasText(/MARK saved/i), 'a confirmation toast should appear after a MARK');
});

// --- guard: real page clicks ARE recorded ------------------------------------
test('clicks on the page are recorded as steps', async () => {
  await deliver({ type: 'recorder:start', intervalMs: 5000 });
  const btn = document.createElement('button'); btn.id = 'app-btn'; document.body.appendChild(btn);
  const before = clickStepCount();
  fireClick(btn);
  assert.equal(clickStepCount(), before + 1, 'normal page clicks must be recorded');
});

// --- #5 RED: do not record clicks on our own overlay -------------------------
test('clicks on the audit overlay are NOT recorded (no self-capture)', async () => {
  await deliver({ type: 'recorder:start', intervalMs: 5000 });
  const overlayBtn = document.querySelector('#__audit_capture_overlay__ button');
  const before = stepCount();
  fireClick(overlayBtn);
  assert.equal(stepCount(), before, 'clicks on the audit overlay must not produce steps');
});

// --- #5 RED: do not record interactions with our own MARK input --------------
test('changes on the MARK input are NOT recorded (no self-capture)', async () => {
  await deliver({ type: 'recorder:start', intervalMs: 5000 });
  await deliver({ type: 'recorder:mark-prompt' });
  const input = document.querySelector('#__audit_mark_input__ input');
  const before = stepCount();
  input.value = 'typing in our own box';
  input.dispatchEvent(new dom.window.Event('change', { bubbles: true }));
  fireClick(input);
  assert.equal(stepCount(), before, 'interactions with the MARK input must not produce steps');
});

// --- VOICE (red): dictate MARK text via Web Speech ---------------------------
// A mic button (#__audit_mark_mic__) in the MARK input starts
// window.SpeechRecognition || webkitSpeechRecognition; onresult fills the input
// value. No SpeechRecognition support => graceful no-op (no throw). This only
// fills the existing MARK input — no output-contract change.

// Minimal fake SpeechRecognition; records instances and start() calls.
function installFakeSR() {
  const created = [];
  class FakeSR {
    constructor() { created.push(this); this.started = false; this.stopped = false; this.lang = ''; this.continuous = false; this.interimResults = false; }
    start() { this.started = true; }
    stop() { this.stopped = true; if (this.onend) this.onend(); }
    // test helper
    _emit(transcript) { if (this.onresult) this.onresult({ results: [[{ transcript }]] }); }
  }
  dom.window.SpeechRecognition = FakeSR;
  dom.window.webkitSpeechRecognition = FakeSR;
  return created;
}
function removeSR() {
  delete dom.window.SpeechRecognition;
  delete dom.window.webkitSpeechRecognition;
}

test('the MARK input has a mic/dictate button', async () => {
  installFakeSR();
  await deliver({ type: 'recorder:start' });
  await deliver({ type: 'recorder:mark-prompt' });
  assert.ok(document.getElementById('__audit_mark_mic__'), 'a #__audit_mark_mic__ control should exist');
  removeSR();
});

test('clicking the mic starts speech recognition', async () => {
  const created = installFakeSR();
  await deliver({ type: 'recorder:start' });
  await deliver({ type: 'recorder:mark-prompt' });
  fireClick(document.getElementById('__audit_mark_mic__'));
  assert.equal(created.length, 1, 'a SpeechRecognition instance must be created');
  assert.equal(created[0].started, true, 'recognition must be started');
  removeSR();
});

test('a speech result fills the MARK input', async () => {
  const created = installFakeSR();
  await deliver({ type: 'recorder:start' });
  await deliver({ type: 'recorder:mark-prompt' });
  fireClick(document.getElementById('__audit_mark_mic__'));
  created[0]._emit('move this card to the sidebar');
  const input = document.querySelector('#__audit_mark_input__ input');
  assert.equal(input.value, 'move this card to the sidebar');
  removeSR();
});

test('no SpeechRecognition support -> clicking mic does not throw', async () => {
  removeSR();
  await deliver({ type: 'recorder:start' });
  await deliver({ type: 'recorder:mark-prompt' });
  const mic = document.getElementById('__audit_mark_mic__');
  assert.ok(mic, 'mic control should still render');
  assert.doesNotThrow(() => fireClick(mic));
});

// --- VOICE refinements (red): continuous, toggle, visible recording state ----

test('dictation is continuous so a pause does not end it', async () => {
  const c = installFakeSR();
  await deliver({ type: 'recorder:start' });
  await deliver({ type: 'recorder:mark-prompt' });
  fireClick(document.getElementById('__audit_mark_mic__'));
  assert.equal(c[0].continuous, true, 'recognition must be continuous (survives pauses)');
  removeSR();
});

test('clicking the mic while listening stops it (toggle, one recognizer)', async () => {
  const c = installFakeSR();
  await deliver({ type: 'recorder:start' });
  await deliver({ type: 'recorder:mark-prompt' });
  const mic = document.getElementById('__audit_mark_mic__');
  fireClick(mic); // start
  fireClick(mic); // stop
  assert.equal(c.length, 1, 'a second click must not spawn a new recognizer');
  assert.equal(c[0].stopped, true, 'a second click must stop recognition');
  removeSR();
});

test('mic shows a recording indicator while listening', async () => {
  installFakeSR();
  await deliver({ type: 'recorder:start' });
  await deliver({ type: 'recorder:mark-prompt' });
  const mic = document.getElementById('__audit_mark_mic__');
  fireClick(mic);
  assert.equal(mic.getAttribute('data-recording'), 'true', 'mic must visibly indicate it is listening');
  removeSR();
});

test('the recording indicator clears when recognition ends', async () => {
  const c = installFakeSR();
  await deliver({ type: 'recorder:start' });
  await deliver({ type: 'recorder:mark-prompt' });
  const mic = document.getElementById('__audit_mark_mic__');
  fireClick(mic);
  if (c[0].onend) c[0].onend();
  assert.notEqual(mic.getAttribute('data-recording'), 'true', 'indicator must clear when recognition ends');
  removeSR();
});

// --- recorder bug (red): MARK input must be dismissed on session stop --------
test('stopping the session removes an open MARK input', async () => {
  await deliver({ type: 'recorder:start' });
  await deliver({ type: 'recorder:mark-prompt' });
  assert.ok(document.getElementById('__audit_mark_input__'), 'input is open');
  await deliver({ type: 'recorder:stop' });
  assert.equal(document.getElementById('__audit_mark_input__'), null, 'MARK input must be removed when the session stops');
});
