// test/worker.test.js
// Integration harness for the service worker — the orchestration layer that had
// NO coverage (which is why the smoke test found bugs the green suite missed).
// Mocks chrome.* + IndexedDB, loads the REAL worker via an importScripts shim,
// and drives it through its message handlers.
//
// Red specs here:
//   * GAP #1: a captured console event must appear in timeline.json (keystone —
//     "every capture path appends a timeline entry"). Currently it does not.
// Guards (should stay green) that isolate other findings:
//   * session:start writes a setViewport step.
//   * a capture message stores a frame + a timeline 'frame' entry.
//   * a mark message writes narration + a timeline 'mark' entry  (proves the
//     WORKER mark path works, so an empty narration.txt in the browser points at
//     the content-script overlay/hotkey, not here).
//
// DO NOT edit this file to pass — fix background/service-worker.js.

const test = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');

require('fake-indexeddb/auto'); // global.indexedDB
const REPO = path.resolve(__dirname, '..');
global.self = global;

// importScripts shim: the worker calls importScripts(chrome.runtime.getURL('lib/..')).
// Our getURL returns the path as-is; load each from disk. jszip is UMD → its
// require() return must be bound to the global the worker expects.
global.importScripts = (...urls) => {
  for (const u of urls) {
    const f = path.join(REPO, u);
    if (/jszip/i.test(u)) global.JSZip = require(f);
    else require(f);
  }
};

function makeChrome() {
  const sessionData = {};
  const dbgEvent = [];
  const dbgDetach = [];
  const calls = { capture: 0, download: [], tabMessages: [], badge: [] };
  const chrome = {
    action: {
      setBadgeBackgroundColor: async () => {},
      setBadgeText: async ({ text }) => { calls.badge.push(text); },
    },
    _calls: calls,
    _fireDbg: (src, method, params) => { for (const f of [...dbgEvent]) f(src, method, params); },
    runtime: {
      getURL: (p) => p,
      onMessage: { addListener: (f) => { chrome._msg = f; } },
      lastError: null,
    },
    storage: {
      session: {
        get: async (k) => (k in sessionData ? { [k]: sessionData[k] } : {}),
        set: async (o) => { Object.assign(sessionData, o); },
        remove: async (k) => { delete sessionData[k]; },
      },
    },
    tabs: {
      captureVisibleTab: async () => {
        calls.capture++;
        return 'data:image/jpeg;base64,' + Buffer.from([0xff, 0xd8, 0xff, 0xd9]).toString('base64');
      },
      sendMessage: async (id, msg) => { calls.tabMessages.push({ id, msg }); },
      query: async () => [{ id: 1, windowId: 1, title: 'Smoke' }],
    },
    downloads: { download: async (o) => { calls.download.push(o); } },
    debugger: {
      onEvent: {
        addListener: (f) => dbgEvent.push(f),
        removeListener: (f) => { const i = dbgEvent.indexOf(f); if (i >= 0) dbgEvent.splice(i, 1); },
      },
      onDetach: {
        addListener: (f) => dbgDetach.push(f),
        removeListener: (f) => { const i = dbgDetach.indexOf(f); if (i >= 0) dbgDetach.splice(i, 1); },
      },
      attach: async () => {},
      sendCommand: async () => {},
      detach: async () => {},
    },
    commands: { onCommand: { addListener: (f) => { chrome._cmd = f; } } },
    windows: { WINDOW_ID_CURRENT: -2 },
  };
  return chrome;
}

global.chrome = makeChrome();
require(path.join(REPO, 'background/service-worker.js'));

const send = (msg, sender = {}) =>
  new Promise((resolve) => { global.chrome._msg(msg, sender, resolve); });
const delay = (ms) => new Promise((r) => setTimeout(r, ms));

test('session:start activates a session and writes a setViewport step', async () => {
  const r = await send({ type: 'session:start' });
  assert.equal(r.ok, true);
  assert.equal(r.session.active, true);
  const steps = await self.AuditStore.getAll('steps');
  assert.equal(steps[0].type, 'setViewport');
});

test('a capture message stores a frame and a timeline frame entry', async () => {
  await send({ type: 'session:start' });
  await send({ type: 'capture', reason: 'interval', route: '/x' }, { tab: { windowId: 1 } });
  const frames = await self.AuditStore.getAll('frames');
  assert.equal(frames.length, 1);
  const tl = await self.AuditStore.getAll('timeline');
  assert.ok(tl.some((e) => e.type === 'frame'), 'a frame timeline entry must exist');
});

// --- GAP #1 (red): console events must reach the timeline --------------------
test('a captured console event is appended to the timeline (keystone)', async () => {
  await send({ type: 'session:start' });
  // Fire a console error through the real debugger tap the worker attached.
  global.chrome._fireDbg({ tabId: 1 }, 'Runtime.consoleAPICalled', {
    type: 'error', args: [{ value: 'boom' }], timestamp: Date.now(),
  });
  await delay(50); // onEvent writes are fire-and-forget
  const tl = await self.AuditStore.getAll('timeline');
  assert.ok(tl.some((e) => e.type === 'console'), 'console events must appear in timeline.json');
});

// --- guard: proves the WORKER mark path works (isolates MARK bugs to content) -
test('a mark message writes narration and a timeline mark entry', async () => {
  await send({ type: 'session:start' });
  await send({ type: 'mark', text: 'MARK 001 — header overlaps, verdict: bug', route: '/checkout' });
  const narration = await self.AuditStore.getAll('narration');
  assert.equal(narration.length, 1);
  assert.match(narration[0].line, /MARK 001/);
  assert.match(narration[0].line, /\(\/checkout\)/);
  const tl = await self.AuditStore.getAll('timeline');
  assert.ok(tl.some((e) => e.type === 'mark'), 'a mark timeline entry must exist');
});

// --- MARK command feedback: a swallowed keypress must become VISIBLE ---------
test('MARK command on an active session asks the page to prompt, no error badge', async () => {
  await send({ type: 'session:start' });
  const before = global.chrome._calls.badge.length;
  await global.chrome._cmd('mark');
  const msgs = global.chrome._calls.tabMessages;
  assert.ok(
    msgs.some((m) => m.msg && m.msg.type === 'recorder:mark-prompt'),
    'must ask the page to open the MARK prompt'
  );
  const after = global.chrome._calls.badge.slice(before);
  assert.ok(!after.includes('X') && !after.includes('!'), 'no failure badge on success');
});

test('MARK command with no active session flashes a warning badge and opens no prompt', async () => {
  await send({ type: 'session:stop' }); // ensure no active session
  const beforeMsgs = global.chrome._calls.tabMessages.length;
  await global.chrome._cmd('mark');
  assert.ok(global.chrome._calls.badge.includes('!'), 'must flash the amber "start a session" badge');
  const newMsgs = global.chrome._calls.tabMessages.slice(beforeMsgs);
  assert.ok(
    !newMsgs.some((m) => m.msg && m.msg.type === 'recorder:mark-prompt'),
    'must NOT open a prompt when there is no session to anchor it to'
  );
});

test('MARK command flashes an error badge when the active tab has no content script', async () => {
  await send({ type: 'session:start' });
  const origSend = global.chrome.tabs.sendMessage;
  global.chrome.tabs.sendMessage = async () => {
    throw new Error('Could not establish connection. Receiving end does not exist.');
  };
  try {
    const before = global.chrome._calls.badge.length;
    await global.chrome._cmd('mark');
    const after = global.chrome._calls.badge.slice(before);
    assert.ok(after.includes('X'), 'must flash the red X when MARK cannot reach the page');
  } finally {
    global.chrome.tabs.sendMessage = origSend;
  }
});

// --- NETWORK keystone (red): failures stored + appended to timeline ----------
test('a captured network failure is stored and appended to the timeline', async () => {
  await send({ type: 'session:start' });
  global.chrome._fireDbg({ tabId: 1 }, 'Network.requestWillBeSent', { requestId: 'z', request: { method: 'GET', url: 'https://api/x' }, timestamp: Date.now() });
  global.chrome._fireDbg({ tabId: 1 }, 'Network.responseReceived', { requestId: 'z', response: { status: 404, url: 'https://api/x' }, timestamp: Date.now() });
  await delay(50);
  const net = await self.AuditStore.getAll('network');
  assert.equal(net.length, 1, 'failed request must be stored');
  const tl = await self.AuditStore.getAll('timeline');
  assert.ok(tl.some((e) => e.type === 'network'), 'network failures must appear in timeline.json');
});

// --- environment (red): an environment message is stored ---------------------
test('an environment message is stored for the package', async () => {
  await send({ type: 'session:start' });
  await send({ type: 'environment', env: { viewport: { w: 1280, h: 800 }, dpr: 2, zoom: 1, ua: 'x', host: 'h', url: 'u', capturedAt: 't', custom: {} } });
  const envs = await self.AuditStore.getAll('environment');
  assert.equal(envs.length, 1, 'the environment record must be stored');
  assert.equal(envs[0].host, 'h');
});

// --- annotation (red): capture-for-draw + store the saved PNG -----------------
test('annotate:capture returns a screenshot dataUrl', async () => {
  await send({ type: 'session:start' });
  const r = await send({ type: 'annotate:capture' }, { tab: { windowId: 1 } });
  assert.ok(r && r.dataUrl, 'must return a captured dataUrl for the draw surface');
});

test('an annotation message stores a *_annotated.png and appends a timeline entry', async () => {
  await send({ type: 'session:start' });
  await send({ type: 'annotation', dataUrl: 'data:image/png;base64,iVBORw0KGgo=' });
  const anns = await self.AuditStore.getAll('annotations');
  assert.equal(anns.length, 1, 'the annotation PNG must be stored');
  assert.match(anns[0].name, /_annotated\.png$/, 'named <ts>_annotated.png');
  const tl = await self.AuditStore.getAll('timeline');
  assert.ok(tl.some((e) => e.type === 'annotation'), 'annotation must appear in timeline.json');
});
